// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ColumnType.
const (
	Boolean ColumnType = "boolean"
	Date    ColumnType = "date"
	Number  ColumnType = "number"
	String  ColumnType = "string"
)

// Valid indicates whether the value is a known member of the ColumnType enum.
func (e ColumnType) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Date:
		return true
	case Number:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusCANCELLED JobStatus = "CANCELLED"
	JobStatusCOMPLETED JobStatus = "COMPLETED"
	JobStatusPAUSED    JobStatus = "PAUSED"
	JobStatusPENDING   JobStatus = "PENDING"
	JobStatusRUNNING   JobStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCANCELLED:
		return true
	case JobStatusCOMPLETED:
		return true
	case JobStatusPAUSED:
		return true
	case JobStatusPENDING:
		return true
	case JobStatusRUNNING:
		return true
	default:
		return false
	}
}

// Defines values for JobType.
const (
	Enrichment JobType = "enrichment"
	Imputation JobType = "imputation"
)

// Valid indicates whether the value is a known member of the JobType enum.
func (e JobType) Valid() bool {
	switch e {
	case Enrichment:
		return true
	case Imputation:
		return true
	default:
		return false
	}
}

// Defines values for RowStage.
const (
	RowStageCANCELLED    RowStage = "CANCELLED"
	RowStageCOMPLETED    RowStage = "COMPLETED"
	RowStageCRAWLED      RowStage = "CRAWLED"
	RowStageDECISIONMADE RowStage = "DECISION_MADE"
	RowStageENRICHED     RowStage = "ENRICHED"
	RowStageFAILED       RowStage = "FAILED"
	RowStagePENDING      RowStage = "PENDING"
	RowStageSERPFETCHED  RowStage = "SERP_FETCHED"
)

// Valid indicates whether the value is a known member of the RowStage enum.
func (e RowStage) Valid() bool {
	switch e {
	case RowStageCANCELLED:
		return true
	case RowStageCOMPLETED:
		return true
	case RowStageCRAWLED:
		return true
	case RowStageDECISIONMADE:
		return true
	case RowStageENRICHED:
		return true
	case RowStageFAILED:
		return true
	case RowStagePENDING:
		return true
	case RowStageSERPFETCHED:
		return true
	default:
		return false
	}
}

// Defines values for SignedURLRequestContentType.
const (
	Applicationjson SignedURLRequestContentType = "application/json"
	Textcsv         SignedURLRequestContentType = "text/csv"
)

// Valid indicates whether the value is a known member of the SignedURLRequestContentType enum.
func (e SignedURLRequestContentType) Valid() bool {
	switch e {
	case Applicationjson:
		return true
	case Textcsv:
		return true
	default:
		return false
	}
}

// ColumnMetadata defines model for ColumnMetadata.
type ColumnMetadata struct {
	Description *string    `json:"description,omitempty"`
	JobType     JobType    `json:"job_type"`
	Name        string     `json:"name"`
	Type        ColumnType `json:"type"`
}

// ColumnType defines model for ColumnType.
type ColumnType string

// CreateCheckoutResponse defines model for CreateCheckoutResponse.
type CreateCheckoutResponse struct {
	CheckoutUrl string `json:"checkout_url"`
	SessionId   string `json:"session_id"`
}

// CreateSubscriptionRequest defines model for CreateSubscriptionRequest.
type CreateSubscriptionRequest struct {
	CancelUrl  string `json:"cancel_url"`
	SuccessUrl string `json:"success_url"`
	TierId     string `json:"tier_id"`
}

// EnrichRequest defines model for EnrichRequest.
type EnrichRequest struct {
	ColumnsMetadata      []ColumnMetadata `json:"columns_metadata"`
	KeyColumnDescription *string          `json:"key_column_description,omitempty"`
	KeyColumns           *[]string        `json:"key_columns,omitempty"`
}

// EnrichResponse defines model for EnrichResponse.
type EnrichResponse struct {
	JobId string `json:"job_id"`
}

// EnrichmentResult defines model for EnrichmentResult.
type EnrichmentResult struct {
	Confidence        *map[string]FieldConfidenceInfo `json:"confidence,omitempty"`
	Error             *string                         `json:"error,omitempty"`
	ExtractedData     map[string]interface{}          `json:"extracted_data"`
	ExtractionHistory []ExtractionHistoryEntry        `json:"extraction_history"`
	Key               string                          `json:"key"`
	Sources           []string                        `json:"sources"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// ExtractionHistoryEntry defines model for ExtractionHistoryEntry.
type ExtractionHistoryEntry struct {
	AttemptNumber int                             `json:"attempt_number"`
	Confidence    *map[string]FieldConfidenceInfo `json:"confidence,omitempty"`
	ExtractedData map[string]interface{}          `json:"extracted_data"`
	Reasoning     string                          `json:"reasoning"`
	Sources       []string                        `json:"sources"`
}

// FieldConfidenceInfo defines model for FieldConfidenceInfo.
type FieldConfidenceInfo struct {
	Reason string  `json:"reason"`
	Score  float64 `json:"score"`
}

// JobProgressResponse defines model for JobProgressResponse.
type JobProgressResponse struct {
	JobId       string         `json:"job_id"`
	RowsByStage map[string]int `json:"rows_by_stage"`
	StartedAt   string         `json:"started_at"`
	Status      JobStatus      `json:"status"`
	TotalRows   int            `json:"total_rows"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JobType defines model for JobType.
type JobType string

// PaginationInfo defines model for PaginationInfo.
type PaginationInfo struct {
	HasMore bool `json:"has_more"`
	Limit   int  `json:"limit"`
	Offset  int  `json:"offset"`
	Total   int  `json:"total"`
}

// RowProgressItem defines model for RowProgressItem.
type RowProgressItem struct {
	Confidence        *map[string]FieldConfidenceInfo `json:"confidence,omitempty"`
	Error             *string                         `json:"error,omitempty"`
	ExtractedData     *map[string]interface{}         `json:"extracted_data,omitempty"`
	ExtractionHistory []ExtractionHistoryEntry        `json:"extraction_history"`
	Key               string                          `json:"key"`
	Sources           *[]string                       `json:"sources,omitempty"`
	Stage             RowStage                        `json:"stage"`
	UpdatedAt         time.Time                       `json:"updated_at"`
}

// RowStage defines model for RowStage.
type RowStage string

// RowsProgressResponse defines model for RowsProgressResponse.
type RowsProgressResponse struct {
	Pagination PaginationInfo    `json:"pagination"`
	Rows       []RowProgressItem `json:"rows"`
}

// SelectKeyRequest defines model for SelectKeyRequest.
type SelectKeyRequest struct {
	ColumnsMetadata *[]ColumnMetadata  `json:"columns_metadata,omitempty"`
	SourceId        openapi_types.UUID `json:"source_id"`
}

// SelectKeyResponse defines model for SelectKeyResponse.
type SelectKeyResponse struct {
	AllKeys     []string `json:"all_keys"`
	Reasoning   string   `json:"reasoning"`
	SelectedKey string   `json:"selected_key"`
}

// SignedURLRequest defines model for SignedURLRequest.
type SignedURLRequest struct {
	ContentType SignedURLRequestContentType `json:"contentType"`

	// Headers CSV column headers, used to generate an AI name for the source
	Headers *[]string `json:"headers,omitempty"`
	Length  int       `json:"length"`
}

// SignedURLRequestContentType defines model for SignedURLRequest.ContentType.
type SignedURLRequestContentType string

// SignedURLResponse defines model for SignedURLResponse.
type SignedURLResponse struct {
	SourceId openapi_types.UUID `json:"sourceId"`
	Url      string             `json:"url"`
}

// SourceDetail defines model for SourceDetail.
type SourceDetail struct {
	CreatedAt time.Time          `json:"created_at"`
	Jobs      []SourceJobSummary `json:"jobs"`
	SourceId  openapi_types.UUID `json:"source_id"`
	Type      string             `json:"type"`
}

// SourceJobSummary defines model for SourceJobSummary.
type SourceJobSummary struct {
	ColumnsMetadata *[]ColumnMetadata `json:"columns_metadata,omitempty"`

	// CostCredits Credits charged for this job run.
	CostCredits          *int       `json:"cost_credits,omitempty"`
	CreatedAt            time.Time  `json:"created_at"`
	JobId                string     `json:"job_id"`
	KeyColumnDescription *string    `json:"key_column_description,omitempty"`
	KeyColumns           *[]string  `json:"key_columns,omitempty"`
	StartedAt            *time.Time `json:"started_at,omitempty"`
	Status               JobStatus  `json:"status"`
	TotalRows            int        `json:"total_rows"`
}

// SourceListResponse defines model for SourceListResponse.
type SourceListResponse struct {
	Sources    []SourceSummary `json:"sources"`
	TotalCount int             `json:"total_count"`
}

// SourceSummary defines model for SourceSummary.
type SourceSummary struct {
	CreatedAt       time.Time          `json:"created_at"`
	JobCount        int                `json:"job_count"`
	LatestJobStatus *JobStatus         `json:"latest_job_status,omitempty"`
	Name            *string            `json:"name,omitempty"`
	SourceId        openapi_types.UUID `json:"source_id"`
	Type            string             `json:"type"`
}

// SubscriptionStatusResponse defines model for SubscriptionStatusResponse.
type SubscriptionStatusResponse struct {
	CancelAtPeriodEnd  bool       `json:"cancel_at_period_end"`
	CurrentPeriodEnd   *time.Time `json:"current_period_end,omitempty"`
	CurrentPeriodStart *time.Time `json:"current_period_start,omitempty"`
	Tier               *string    `json:"tier,omitempty"`
	TokensIncluded     int64      `json:"tokens_included"`
	TokensUsed         int64      `json:"tokens_used"`
}

// TierResponse defines model for TierResponse.
type TierResponse struct {
	DisplayName              string `json:"display_name"`
	Id                       string `json:"id"`
	IncludedTokens           int64  `json:"included_tokens"`
	MonthlyPriceCents        int64  `json:"monthly_price_cents"`
	OveragePriceCentsDecimal string `json:"overage_price_cents_decimal"`
}

// UpgradeSubscriptionRequest defines model for UpgradeSubscriptionRequest.
type UpgradeSubscriptionRequest struct {
	TierId string `json:"tier_id"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

// GetJobResultsParams defines parameters for GetJobResults.
type GetJobResultsParams struct {
	Start *int `form:"start,omitempty" json:"start,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetRowsProgressParams defines parameters for GetRowsProgress.
type GetRowsProgressParams struct {
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Stage  *string `form:"stage,omitempty" json:"stage,omitempty"`
	Sort   *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePortalSessionParams defines parameters for CreatePortalSession.
type CreatePortalSessionParams struct {
	ReturnUrl string `form:"return_url" json:"return_url"`
}

// HandleStripeWebhookParams defines parameters for HandleStripeWebhook.
type HandleStripeWebhookParams struct {
	StripeSignature string `json:"Stripe-Signature"`
}

// UploadFileForEnrichmentJSONRequestBody defines body for UploadFileForEnrichment for application/json ContentType.
type UploadFileForEnrichmentJSONRequestBody = SignedURLRequest

// SelectKeyJSONRequestBody defines body for SelectKey for application/json ContentType.
type SelectKeyJSONRequestBody = SelectKeyRequest

// EnrichSourceJSONRequestBody defines body for EnrichSource for application/json ContentType.
type EnrichSourceJSONRequestBody = EnrichRequest

// CreateSubscriptionCheckoutJSONRequestBody defines body for CreateSubscriptionCheckout for application/json ContentType.
type CreateSubscriptionCheckoutJSONRequestBody = CreateSubscriptionRequest

// UpgradeSubscriptionJSONRequestBody defines body for UpgradeSubscription for application/json ContentType.
type UpgradeSubscriptionJSONRequestBody = UpgradeSubscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a pending enrichment job and get a signed upload URL
	// (POST /enrichment-signed-url)
	UploadFileForEnrichment(w http.ResponseWriter, r *http.Request)
	// Cancel a running enrichment job
	// (POST /jobs/{jobID}/cancel)
	CancelJob(w http.ResponseWriter, r *http.Request, jobID string)
	// Get progress summary for a job
	// (GET /jobs/{jobID}/progress)
	GetJobProgress(w http.ResponseWriter, r *http.Request, jobID string)
	// Get enrichment results for a job
	// (GET /jobs/{jobID}/results)
	GetJobResults(w http.ResponseWriter, r *http.Request, jobID string, params GetJobResultsParams)
	// Get per-row progress for a job
	// (GET /jobs/{jobID}/rows)
	GetRowsProgress(w http.ResponseWriter, r *http.Request, jobID string, params GetRowsProgressParams)
	// Get the current authenticated user's profile
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Use AI to select the best key column from a source's CSV
	// (POST /select-key)
	SelectKey(w http.ResponseWriter, r *http.Request)
	// List sources for the authenticated user
	// (GET /sources)
	ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams)
	// Get source details with all enrichment runs
	// (GET /sources/{sourceID})
	GetSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID)
	// Get the raw CSV data for a source
	// (GET /sources/{sourceID}/data)
	GetSourceData(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID)
	// Start a new enrichment run for a source
	// (POST /sources/{sourceID}/enrich)
	EnrichSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID)
	// Create a Stripe checkout session for a subscription
	// (POST /subscribe)
	CreateSubscriptionCheckout(w http.ResponseWriter, r *http.Request)
	// Get the current user's subscription status
	// (GET /subscription)
	GetSubscriptionStatus(w http.ResponseWriter, r *http.Request)
	// Cancel the current user's subscription
	// (POST /subscription/cancel)
	CancelSubscription(w http.ResponseWriter, r *http.Request)
	// Create a Stripe customer portal session
	// (POST /subscription/portal)
	CreatePortalSession(w http.ResponseWriter, r *http.Request, params CreatePortalSessionParams)
	// Upgrade the current user's subscription to a higher tier
	// (POST /subscription/upgrade)
	UpgradeSubscription(w http.ResponseWriter, r *http.Request)
	// List available subscription tiers
	// (GET /tiers)
	ListTiers(w http.ResponseWriter, r *http.Request)
	// Handle Stripe webhook events
	// (POST /webhooks/stripe)
	HandleStripeWebhook(w http.ResponseWriter, r *http.Request, params HandleStripeWebhookParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadFileForEnrichment operation middleware
func (siw *ServerInterfaceWrapper) UploadFileForEnrichment(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadFileForEnrichment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelJob operation middleware
func (siw *ServerInterfaceWrapper) CancelJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelJob(w, r, jobID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobProgress operation middleware
func (siw *ServerInterfaceWrapper) GetJobProgress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobProgress(w, r, jobID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobResults operation middleware
func (siw *ServerInterfaceWrapper) GetJobResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJobResultsParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobResults(w, r, jobID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRowsProgress operation middleware
func (siw *ServerInterfaceWrapper) GetRowsProgress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRowsProgressParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "stage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "stage", r.URL.Query(), &params.Stage, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRowsProgress(w, r, jobID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SelectKey operation middleware
func (siw *ServerInterfaceWrapper) SelectKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSources operation middleware
func (siw *ServerInterfaceWrapper) ListSources(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSourcesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceID" -------------
	var sourceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sourceID", mux.Vars(r)["sourceID"], &sourceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, sourceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSourceData operation middleware
func (siw *ServerInterfaceWrapper) GetSourceData(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceID" -------------
	var sourceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sourceID", mux.Vars(r)["sourceID"], &sourceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSourceData(w, r, sourceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrichSource operation middleware
func (siw *ServerInterfaceWrapper) EnrichSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceID" -------------
	var sourceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sourceID", mux.Vars(r)["sourceID"], &sourceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrichSource(w, r, sourceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubscriptionCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscriptionCheckout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscriptionCheckout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscriptionStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSubscriptionStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscriptionStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelSubscription operation middleware
func (siw *ServerInterfaceWrapper) CancelSubscription(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePortalSession operation middleware
func (siw *ServerInterfaceWrapper) CreatePortalSession(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePortalSessionParams

	// ------------- Required query parameter "return_url" -------------

	if paramValue := r.URL.Query().Get("return_url"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "return_url"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "return_url", r.URL.Query(), &params.ReturnUrl, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "return_url", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePortalSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpgradeSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpgradeSubscription(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpgradeSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTiers operation middleware
func (siw *ServerInterfaceWrapper) ListTiers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTiers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleStripeWebhook operation middleware
func (siw *ServerInterfaceWrapper) HandleStripeWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleStripeWebhookParams

	headers := r.Header

	// ------------- Required header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Stripe-Signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Stripe-Signature", Err: err})
			return
		}

		params.StripeSignature = StripeSignature

	} else {
		err = fmt.Errorf("Header parameter Stripe-Signature is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Stripe-Signature", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleStripeWebhook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/enrichment-signed-url", wrapper.UploadFileForEnrichment).Methods("POST")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/cancel", wrapper.CancelJob).Methods("POST")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/progress", wrapper.GetJobProgress).Methods("GET")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/results", wrapper.GetJobResults).Methods("GET")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/rows", wrapper.GetRowsProgress).Methods("GET")

	r.HandleFunc(options.BaseURL+"/me", wrapper.GetMe).Methods("GET")

	r.HandleFunc(options.BaseURL+"/select-key", wrapper.SelectKey).Methods("POST")

	r.HandleFunc(options.BaseURL+"/sources", wrapper.ListSources).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sources/{sourceID}", wrapper.GetSource).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sources/{sourceID}/data", wrapper.GetSourceData).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sources/{sourceID}/enrich", wrapper.EnrichSource).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscribe", wrapper.CreateSubscriptionCheckout).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscription", wrapper.GetSubscriptionStatus).Methods("GET")

	r.HandleFunc(options.BaseURL+"/subscription/cancel", wrapper.CancelSubscription).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscription/portal", wrapper.CreatePortalSession).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscription/upgrade", wrapper.UpgradeSubscription).Methods("POST")

	r.HandleFunc(options.BaseURL+"/tiers", wrapper.ListTiers).Methods("GET")

	r.HandleFunc(options.BaseURL+"/webhooks/stripe", wrapper.HandleStripeWebhook).Methods("POST")

	return r
}

type UploadFileForEnrichmentRequestObject struct {
	Body *UploadFileForEnrichmentJSONRequestBody
}

type UploadFileForEnrichmentResponseObject interface {
	VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error
}

type UploadFileForEnrichment200JSONResponse SignedURLResponse

func (response UploadFileForEnrichment200JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UploadFileForEnrichment400JSONResponse ErrorResponse

func (response UploadFileForEnrichment400JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadFileForEnrichment401JSONResponse ErrorResponse

func (response UploadFileForEnrichment401JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UploadFileForEnrichment500JSONResponse ErrorResponse

func (response UploadFileForEnrichment500JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CancelJobRequestObject struct {
	JobID string `json:"jobID"`
}

type CancelJobResponseObject interface {
	VisitCancelJobResponse(w http.ResponseWriter) error
}

type CancelJob200JSONResponse struct {
	Message string `json:"message"`
}

func (response CancelJob200JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelJob404JSONResponse ErrorResponse

func (response CancelJob404JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelJob500JSONResponse ErrorResponse

func (response CancelJob500JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobProgressRequestObject struct {
	JobID string `json:"jobID"`
}

type GetJobProgressResponseObject interface {
	VisitGetJobProgressResponse(w http.ResponseWriter) error
}

type GetJobProgress200JSONResponse JobProgressResponse

func (response GetJobProgress200JSONResponse) VisitGetJobProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobProgress404JSONResponse ErrorResponse

func (response GetJobProgress404JSONResponse) VisitGetJobProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobResultsRequestObject struct {
	JobID  string `json:"jobID"`
	Params GetJobResultsParams
}

type GetJobResultsResponseObject interface {
	VisitGetJobResultsResponse(w http.ResponseWriter) error
}

type GetJobResults200JSONResponse []EnrichmentResult

func (response GetJobResults200JSONResponse) VisitGetJobResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobResults500JSONResponse ErrorResponse

func (response GetJobResults500JSONResponse) VisitGetJobResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRowsProgressRequestObject struct {
	JobID  string `json:"jobID"`
	Params GetRowsProgressParams
}

type GetRowsProgressResponseObject interface {
	VisitGetRowsProgressResponse(w http.ResponseWriter) error
}

type GetRowsProgress200JSONResponse RowsProgressResponse

func (response GetRowsProgress200JSONResponse) VisitGetRowsProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRowsProgress400JSONResponse ErrorResponse

func (response GetRowsProgress400JSONResponse) VisitGetRowsProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRowsProgress500JSONResponse ErrorResponse

func (response GetRowsProgress500JSONResponse) VisitGetRowsProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse UserResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401JSONResponse ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SelectKeyRequestObject struct {
	Body *SelectKeyJSONRequestBody
}

type SelectKeyResponseObject interface {
	VisitSelectKeyResponse(w http.ResponseWriter) error
}

type SelectKey200JSONResponse SelectKeyResponse

func (response SelectKey200JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey400JSONResponse ErrorResponse

func (response SelectKey400JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey401JSONResponse ErrorResponse

func (response SelectKey401JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey403JSONResponse ErrorResponse

func (response SelectKey403JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey404JSONResponse ErrorResponse

func (response SelectKey404JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey500JSONResponse ErrorResponse

func (response SelectKey500JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListSourcesRequestObject struct {
	Params ListSourcesParams
}

type ListSourcesResponseObject interface {
	VisitListSourcesResponse(w http.ResponseWriter) error
}

type ListSources200JSONResponse SourceListResponse

func (response ListSources200JSONResponse) VisitListSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSources401JSONResponse ErrorResponse

func (response ListSources401JSONResponse) VisitListSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListSources500JSONResponse ErrorResponse

func (response ListSources500JSONResponse) VisitListSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRequestObject struct {
	SourceID openapi_types.UUID `json:"sourceID"`
}

type GetSourceResponseObject interface {
	VisitGetSourceResponse(w http.ResponseWriter) error
}

type GetSource200JSONResponse SourceDetail

func (response GetSource200JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSource401JSONResponse ErrorResponse

func (response GetSource401JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSource403JSONResponse ErrorResponse

func (response GetSource403JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSource404JSONResponse ErrorResponse

func (response GetSource404JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSource500JSONResponse ErrorResponse

func (response GetSource500JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceDataRequestObject struct {
	SourceID openapi_types.UUID `json:"sourceID"`
}

type GetSourceDataResponseObject interface {
	VisitGetSourceDataResponse(w http.ResponseWriter) error
}

type GetSourceData200JSONResponse struct {
	Headers []string   `json:"headers"`
	Rows    [][]string `json:"rows"`
}

func (response GetSourceData200JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData401JSONResponse ErrorResponse

func (response GetSourceData401JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData403JSONResponse ErrorResponse

func (response GetSourceData403JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData404JSONResponse ErrorResponse

func (response GetSourceData404JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData500JSONResponse ErrorResponse

func (response GetSourceData500JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSourceRequestObject struct {
	SourceID openapi_types.UUID `json:"sourceID"`
	Body     *EnrichSourceJSONRequestBody
}

type EnrichSourceResponseObject interface {
	VisitEnrichSourceResponse(w http.ResponseWriter) error
}

type EnrichSource200JSONResponse EnrichResponse

func (response EnrichSource200JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource400JSONResponse ErrorResponse

func (response EnrichSource400JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource401JSONResponse ErrorResponse

func (response EnrichSource401JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource402JSONResponse ErrorResponse

func (response EnrichSource402JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(402)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource403JSONResponse ErrorResponse

func (response EnrichSource403JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource404JSONResponse ErrorResponse

func (response EnrichSource404JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource500JSONResponse ErrorResponse

func (response EnrichSource500JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionCheckoutRequestObject struct {
	Body *CreateSubscriptionCheckoutJSONRequestBody
}

type CreateSubscriptionCheckoutResponseObject interface {
	VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error
}

type CreateSubscriptionCheckout200JSONResponse CreateCheckoutResponse

func (response CreateSubscriptionCheckout200JSONResponse) VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionCheckout400JSONResponse ErrorResponse

func (response CreateSubscriptionCheckout400JSONResponse) VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionCheckout500JSONResponse ErrorResponse

func (response CreateSubscriptionCheckout500JSONResponse) VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionStatusRequestObject struct {
}

type GetSubscriptionStatusResponseObject interface {
	VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error
}

type GetSubscriptionStatus200JSONResponse SubscriptionStatusResponse

func (response GetSubscriptionStatus200JSONResponse) VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionStatus400JSONResponse ErrorResponse

func (response GetSubscriptionStatus400JSONResponse) VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscriptionRequestObject struct {
}

type CancelSubscriptionResponseObject interface {
	VisitCancelSubscriptionResponse(w http.ResponseWriter) error
}

type CancelSubscription200JSONResponse struct {
	Message string `json:"message"`
}

func (response CancelSubscription200JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscription400JSONResponse ErrorResponse

func (response CancelSubscription400JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscription500JSONResponse ErrorResponse

func (response CancelSubscription500JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePortalSessionRequestObject struct {
	Params CreatePortalSessionParams
}

type CreatePortalSessionResponseObject interface {
	VisitCreatePortalSessionResponse(w http.ResponseWriter) error
}

type CreatePortalSession200JSONResponse struct {
	Url string `json:"url"`
}

func (response CreatePortalSession200JSONResponse) VisitCreatePortalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePortalSession400JSONResponse ErrorResponse

func (response CreatePortalSession400JSONResponse) VisitCreatePortalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePortalSession500JSONResponse ErrorResponse

func (response CreatePortalSession500JSONResponse) VisitCreatePortalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeSubscriptionRequestObject struct {
	Body *UpgradeSubscriptionJSONRequestBody
}

type UpgradeSubscriptionResponseObject interface {
	VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error
}

type UpgradeSubscription200JSONResponse struct {
	Message string `json:"message"`
}

func (response UpgradeSubscription200JSONResponse) VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeSubscription400JSONResponse ErrorResponse

func (response UpgradeSubscription400JSONResponse) VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeSubscription500JSONResponse ErrorResponse

func (response UpgradeSubscription500JSONResponse) VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTiersRequestObject struct {
}

type ListTiersResponseObject interface {
	VisitListTiersResponse(w http.ResponseWriter) error
}

type ListTiers200JSONResponse []TierResponse

func (response ListTiers200JSONResponse) VisitListTiersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleStripeWebhookRequestObject struct {
	Params HandleStripeWebhookParams
	Body   io.Reader
}

type HandleStripeWebhookResponseObject interface {
	VisitHandleStripeWebhookResponse(w http.ResponseWriter) error
}

type HandleStripeWebhook200Response struct {
}

func (response HandleStripeWebhook200Response) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type HandleStripeWebhook400JSONResponse ErrorResponse

func (response HandleStripeWebhook400JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleStripeWebhook401JSONResponse ErrorResponse

func (response HandleStripeWebhook401JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type HandleStripeWebhook500JSONResponse ErrorResponse

func (response HandleStripeWebhook500JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a pending enrichment job and get a signed upload URL
	// (POST /enrichment-signed-url)
	UploadFileForEnrichment(ctx context.Context, request UploadFileForEnrichmentRequestObject) (UploadFileForEnrichmentResponseObject, error)
	// Cancel a running enrichment job
	// (POST /jobs/{jobID}/cancel)
	CancelJob(ctx context.Context, request CancelJobRequestObject) (CancelJobResponseObject, error)
	// Get progress summary for a job
	// (GET /jobs/{jobID}/progress)
	GetJobProgress(ctx context.Context, request GetJobProgressRequestObject) (GetJobProgressResponseObject, error)
	// Get enrichment results for a job
	// (GET /jobs/{jobID}/results)
	GetJobResults(ctx context.Context, request GetJobResultsRequestObject) (GetJobResultsResponseObject, error)
	// Get per-row progress for a job
	// (GET /jobs/{jobID}/rows)
	GetRowsProgress(ctx context.Context, request GetRowsProgressRequestObject) (GetRowsProgressResponseObject, error)
	// Get the current authenticated user's profile
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Use AI to select the best key column from a source's CSV
	// (POST /select-key)
	SelectKey(ctx context.Context, request SelectKeyRequestObject) (SelectKeyResponseObject, error)
	// List sources for the authenticated user
	// (GET /sources)
	ListSources(ctx context.Context, request ListSourcesRequestObject) (ListSourcesResponseObject, error)
	// Get source details with all enrichment runs
	// (GET /sources/{sourceID})
	GetSource(ctx context.Context, request GetSourceRequestObject) (GetSourceResponseObject, error)
	// Get the raw CSV data for a source
	// (GET /sources/{sourceID}/data)
	GetSourceData(ctx context.Context, request GetSourceDataRequestObject) (GetSourceDataResponseObject, error)
	// Start a new enrichment run for a source
	// (POST /sources/{sourceID}/enrich)
	EnrichSource(ctx context.Context, request EnrichSourceRequestObject) (EnrichSourceResponseObject, error)
	// Create a Stripe checkout session for a subscription
	// (POST /subscribe)
	CreateSubscriptionCheckout(ctx context.Context, request CreateSubscriptionCheckoutRequestObject) (CreateSubscriptionCheckoutResponseObject, error)
	// Get the current user's subscription status
	// (GET /subscription)
	GetSubscriptionStatus(ctx context.Context, request GetSubscriptionStatusRequestObject) (GetSubscriptionStatusResponseObject, error)
	// Cancel the current user's subscription
	// (POST /subscription/cancel)
	CancelSubscription(ctx context.Context, request CancelSubscriptionRequestObject) (CancelSubscriptionResponseObject, error)
	// Create a Stripe customer portal session
	// (POST /subscription/portal)
	CreatePortalSession(ctx context.Context, request CreatePortalSessionRequestObject) (CreatePortalSessionResponseObject, error)
	// Upgrade the current user's subscription to a higher tier
	// (POST /subscription/upgrade)
	UpgradeSubscription(ctx context.Context, request UpgradeSubscriptionRequestObject) (UpgradeSubscriptionResponseObject, error)
	// List available subscription tiers
	// (GET /tiers)
	ListTiers(ctx context.Context, request ListTiersRequestObject) (ListTiersResponseObject, error)
	// Handle Stripe webhook events
	// (POST /webhooks/stripe)
	HandleStripeWebhook(ctx context.Context, request HandleStripeWebhookRequestObject) (HandleStripeWebhookResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// UploadFileForEnrichment operation middleware
func (sh *strictHandler) UploadFileForEnrichment(w http.ResponseWriter, r *http.Request) {
	var request UploadFileForEnrichmentRequestObject

	var body UploadFileForEnrichmentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadFileForEnrichment(ctx, request.(UploadFileForEnrichmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadFileForEnrichment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadFileForEnrichmentResponseObject); ok {
		if err := validResponse.VisitUploadFileForEnrichmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelJob operation middleware
func (sh *strictHandler) CancelJob(w http.ResponseWriter, r *http.Request, jobID string) {
	var request CancelJobRequestObject

	request.JobID = jobID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelJob(ctx, request.(CancelJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelJobResponseObject); ok {
		if err := validResponse.VisitCancelJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobProgress operation middleware
func (sh *strictHandler) GetJobProgress(w http.ResponseWriter, r *http.Request, jobID string) {
	var request GetJobProgressRequestObject

	request.JobID = jobID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobProgress(ctx, request.(GetJobProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobProgress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobProgressResponseObject); ok {
		if err := validResponse.VisitGetJobProgressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobResults operation middleware
func (sh *strictHandler) GetJobResults(w http.ResponseWriter, r *http.Request, jobID string, params GetJobResultsParams) {
	var request GetJobResultsRequestObject

	request.JobID = jobID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobResults(ctx, request.(GetJobResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResultsResponseObject); ok {
		if err := validResponse.VisitGetJobResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRowsProgress operation middleware
func (sh *strictHandler) GetRowsProgress(w http.ResponseWriter, r *http.Request, jobID string, params GetRowsProgressParams) {
	var request GetRowsProgressRequestObject

	request.JobID = jobID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRowsProgress(ctx, request.(GetRowsProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRowsProgress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRowsProgressResponseObject); ok {
		if err := validResponse.VisitGetRowsProgressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SelectKey operation middleware
func (sh *strictHandler) SelectKey(w http.ResponseWriter, r *http.Request) {
	var request SelectKeyRequestObject

	var body SelectKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SelectKey(ctx, request.(SelectKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SelectKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SelectKeyResponseObject); ok {
		if err := validResponse.VisitSelectKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSources operation middleware
func (sh *strictHandler) ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams) {
	var request ListSourcesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSources(ctx, request.(ListSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSourcesResponseObject); ok {
		if err := validResponse.VisitListSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSource operation middleware
func (sh *strictHandler) GetSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID) {
	var request GetSourceRequestObject

	request.SourceID = sourceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSource(ctx, request.(GetSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceResponseObject); ok {
		if err := validResponse.VisitGetSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSourceData operation middleware
func (sh *strictHandler) GetSourceData(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID) {
	var request GetSourceDataRequestObject

	request.SourceID = sourceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSourceData(ctx, request.(GetSourceDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSourceData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceDataResponseObject); ok {
		if err := validResponse.VisitGetSourceDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrichSource operation middleware
func (sh *strictHandler) EnrichSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID) {
	var request EnrichSourceRequestObject

	request.SourceID = sourceID

	var body EnrichSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnrichSource(ctx, request.(EnrichSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrichSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnrichSourceResponseObject); ok {
		if err := validResponse.VisitEnrichSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSubscriptionCheckout operation middleware
func (sh *strictHandler) CreateSubscriptionCheckout(w http.ResponseWriter, r *http.Request) {
	var request CreateSubscriptionCheckoutRequestObject

	var body CreateSubscriptionCheckoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscriptionCheckout(ctx, request.(CreateSubscriptionCheckoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscriptionCheckout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubscriptionCheckoutResponseObject); ok {
		if err := validResponse.VisitCreateSubscriptionCheckoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscriptionStatus operation middleware
func (sh *strictHandler) GetSubscriptionStatus(w http.ResponseWriter, r *http.Request) {
	var request GetSubscriptionStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscriptionStatus(ctx, request.(GetSubscriptionStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscriptionStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionStatusResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelSubscription operation middleware
func (sh *strictHandler) CancelSubscription(w http.ResponseWriter, r *http.Request) {
	var request CancelSubscriptionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelSubscription(ctx, request.(CancelSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelSubscriptionResponseObject); ok {
		if err := validResponse.VisitCancelSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePortalSession operation middleware
func (sh *strictHandler) CreatePortalSession(w http.ResponseWriter, r *http.Request, params CreatePortalSessionParams) {
	var request CreatePortalSessionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePortalSession(ctx, request.(CreatePortalSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePortalSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePortalSessionResponseObject); ok {
		if err := validResponse.VisitCreatePortalSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpgradeSubscription operation middleware
func (sh *strictHandler) UpgradeSubscription(w http.ResponseWriter, r *http.Request) {
	var request UpgradeSubscriptionRequestObject

	var body UpgradeSubscriptionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpgradeSubscription(ctx, request.(UpgradeSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpgradeSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpgradeSubscriptionResponseObject); ok {
		if err := validResponse.VisitUpgradeSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTiers operation middleware
func (sh *strictHandler) ListTiers(w http.ResponseWriter, r *http.Request) {
	var request ListTiersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTiers(ctx, request.(ListTiersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTiers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTiersResponseObject); ok {
		if err := validResponse.VisitListTiersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleStripeWebhook operation middleware
func (sh *strictHandler) HandleStripeWebhook(w http.ResponseWriter, r *http.Request, params HandleStripeWebhookParams) {
	var request HandleStripeWebhookRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleStripeWebhook(ctx, request.(HandleStripeWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleStripeWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleStripeWebhookResponseObject); ok {
		if err := validResponse.VisitHandleStripeWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW3PbtvL/Khj8/zN9YSKnTc+D31xbbpXjuB4pbh8yGQ5EriQkJMACoF0dj777GVx4",
	"Byk6jWSfid8kEVgsdn+7wF6oBxzxNOMMmJL49AHLaAMpMR/PeZKn7D0oEhNF9C+Z4BkIRcE8j0FGgmaK",
	"cqa/sjxJyDIBfKpEDgFW2wzwKZZKULbGuwB/5svQ/viA/1/ACp/i/5tUq0/c0pN3fPlBD9sFmJHUDO/Q",
	"GkPH8m9J7QIs4K+cCojx6UdL11GpMfap5JovP0Ok9Eo1KqcPGFieagKOkwCzPF2CwAFecp4AYTjAMVF1",
	"UhXT5wKIgvMNRF94ruYgM84kdAUbuRFhLhLv7iVISTkLaex53Npqg1hjqne3hsVFvixVO4e/cpDKwyVh",
	"EST9POZRBFL2PlcUxKgNFAObJIP6+r6dTJmg0aafe6NWGaY1eFMFqRyHqtIqdgFOKZvZmW9KPogQZKsf",
	"foFtaNcKH2sv1VTZ4K4zsIeS46GNh/bGh4TXh1BtMWN058b1L5EC04aQJ14VsRWNgUWGARLHVIuOJDeN",
	"UUO6uqSQxOclmRlb8QF5VbyBEFyM0hH8rQSJFMRhASI/n30L2enaIDdUKi62o3E4Laf+ZmdOmRLbyjc2",
	"IOi3UJ6LCPZgaxBLmnJHBhVh7/68WNDy7kdbClKSNeyHWzHQu4ZfXp3FiFKQZip0jr1akzIFaxCa1hMi",
	"85/hTQCRnGnRHQYQLeENYqPixacun4A6urIk/HuJuDDaWXGREoVPccxzLdlyLcdjewt2YsGel7d3fHkj",
	"+FqAlF/hIgMs+L0Ml9tQKofqPgR1kdfhRSoitHiJ8otBEZXLETeuhR2ol+CKJKHm0ceC38E3ZrU32GCy",
	"ZKlHsIuS4eKqdTO9vphd/4oDPL+9vrafbs5uF9MLHODzs+vz6dWV/fz7+5ur6YfphffyVdwqa5ShPIJw",
	"gGma5YqYw9k3/YasKTOP/VDcEBmmDnJucnEj3AU4oSlVfo3y1UpCzzMj1BFasONKWsV6QcWVT9pzfl/A",
	"WN9fvocDeKx/fcYH8vBlz5jXem9oNOf3CzNuF+A80wFL4UEqd0kUvFI0rXnMnlPX3gIKW6+RG33+l+x4",
	"zX4xnd+El9MP578ZM7+Yns8Ws9+vw/dnF1Nt9vOzP60DmF7PZ25Q5QsCfHk2u2o5C5+Fz/m93O/Ws9IP",
	"7JNxy2M4vz8aTm3r3Hf0Otdb488n6QUkEKl/w/YYgdFeqBq8u1OyBF6e2wNlEHPV1D277NMjSZLwC2wf",
	"ddnZe38yy0Ic+g28vYX66KBiaN/NaEHXDOLb+dWACpkCptrHnYK/1SSSd3qxLEtoZGAy+Sx7jrwNkBhE",
	"N9WDzxd/IAsT5MYEKJcQI8XRGhgIogARhs5miJEU0IoLpDaArNL0WTta4AmwtdqYIIAymuqNVEF233FY",
	"339JYo8o+3BieZ6NgWiA/bmOFncuD1PQ9fJlHl6AIjTxqNfkaB7jsE2Ka7zrscvry1iepsR/hj3Gdqt0",
	"3VijLlNztb26TfTLq8bwU3q1iEsVRgJiqny2Yx+gaEPEGmJnG1Siz3yJRM5e48AXcH6dyvsCkKdPSrUD",
	"F++W9jJztOjGLdQKc2pa6UflFZVqn3t5rGkO2KVlMOI5UyM2WEXj9Xn9m+m3r68EaC+jAU6IAqlCPeor",
	"9FxUDvZj6Gkc2ZCoa9l3u6GBUoFNghMVZiAoj0NgsT8EjXIhgLXHfZ3dtWgZU/56aorCuFhP8S/AZEhZ",
	"lOQxNPmnTP3rrdd3uln6gjJqRie2rqZ3WQj8GvCp9QOFgRxnTGWWkG3YW/HqceUFJ6HlbKRMUs7UJtmG",
	"maARhFFR/Bsxk9+BIGuozwxjiGhKRlx9jEE0dupnpbut4YV94r7N1oLE40pZj65FeReUQ/qF1N3lOhpc",
	"USFVv94T0v+0xV2NUn1e4BbvMm1iligXVG0X2olaVn8BIkCc5fbevTTfLgtkvPvzgz4PzWjtYMzTCikb",
	"pTK82xlg2jRZ8/pzlmYJXBBFUJV8Q2c3M02BKm37tSH29zsQ0k5+8/rk9YkBYQaMZBSf4p9en7z+yYS9",
	"amOYn1R0X0lzvX/lbuUZt6rXWrFheYxP8W2WcBJf0gQuuZjWE4LCouUXHm9rQZWJHdvRU1k333t8t2O3",
	"XVOH2vGZHyyMzI5+PDk5xPoOqIaBpo7sIHQ7vyqjuVhL/e03ZKRZ8fEw8QuJkSiEpNd+c7y1bxnJ1YYL",
	"+h+78Z+PufEZUyAYSZAEcQcC2VSoMdXi8uWq9IigDFhM2bpuTDqOICxGa1CIIGsCKDco1yrVhkbW0t1u",
	"Jf6kKU/0x8nDZ76cXewm9kTrN5lz8/wdXxq7EyQFZdIEHx8w1TvQtoiLGxg2RHEb5EFNXG2n9ukfGsA3",
	"Lx52lfSOL5EVU1LYxtvjQUSvzrhCK56zZwpQIxtEdETLugAdAcLM5T41u2vwoPBXULU63DOF4p5wpZNu",
	"7lF2KYwnRlpDx7+CKhlD7meTziAjVSxM38c+Dc/dqMMoOHB0/spBbCtCNqKpT4xhRUyXyokvYvBTKapw",
	"I6n8U7CNq1K12266dYUOCqo5qNDZc3Q6GpDQYfVxkHR5oT481mtEx0VkWdo9GCR/PglwSv52SfaTRxAt",
	"y/xdopgkia+Y00OI91ldraxoUpYemof01d7aoAemc37fctZPd2V+lvaZgXglakLaZ5027O0zx/e2UedA",
	"Sm8E9L4wQYLQG1nRBJ44RunIWW0AuSwd0gOBKc2IDgUkiB9kyXcldf2gELutTb5ydUx/GFAWWQ8VK7dL",
	"1ceOlTtFZF+s7Iq4SIvqe46R3578dLzFL7lY0jgGdvQLsS2DPPPo61YCOpshxZG1Y+MNliCVRmlRuV8J",
	"niLiavI/SHS++MPvgmslKq8fvqJSLco6ku9K9CRXmW9+vd5flmuU+jy6088RX6FCoi95rRZwjYCcdMqu",
	"ke7xVcNpIcoGVCcPrrviYjd0e1gU7Sj7r/EFvcGb/L4OpsMD0HWM9Put2A14OSxeDovabVHW0SHRPVUb",
	"RJKkEU3npgo31u4mRZPNsPFd2JcC/kcMsNXxXbXHPaKBsN0COn7qYPdnwYxbYUwOe07u9aGPir6mF4/w",
	"4hEa8aOoAcTF6WUH52g/YF1IfxRpc4tPchR/+5C1+c7pkePV1jubw3lc1333nYesPx5v8RuydVlph4cX",
	"p/esnN5CGwQiiMF969oz0vXZPqMlDNTNO+/WF38FcKAMWv/L/Ed2TT1/fOBRVTEGuf8pQK5v8iWZ3tcC",
	"slCCZoCituAcamvKr2F3SZPEvF9Sx27ZBN57Z+80ph4y/T7QButzMrXRSJZtwEfFjCkIDJXL61l5l4eX",
	"Hr7H6Glkl86iqf/n3lfT0GKrweaIirzmiESK3kHTfp5xp80eZI2DVMaFe9946AC7MaMW1s2My/gKULlg",
	"7n9bnqoRbPTLWWOAaoVQOtvb+dUTexvEBUqplJStyyMhl4qntm37+Z9fjlmUNSQ7Dri57fUe6vLtNIMf",
	"6M410HZ+gEvXsV2yE/TLdaxTcrOC2XvCK44I2tD1BgQy77304Vs/HK65faAu4XfwnrHGmysj+sWKOpfd",
	"g6fEQ+4INa/6tITjduSXyD0sN5x/kRNpPEa/sf9GWJyA9St/2kk9x5TNmlbnlJ3zakHXjKjc/Q3Mo06r",
	"MQ6FRwrUK6kEkLSpjTJttaSMmAO0vchYD9JUiJMCygSPQMrvLO8zY3ckobHphbdqfUYexL1+g08/fqqb",
	"icVwcTg66CO4c69HeSykSaz5Fs/HTxqddnELf3MZwhOS0cndG7z7tPtvAAAA///TeLmGCFIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
