// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ColumnType.
const (
	Boolean ColumnType = "boolean"
	Date    ColumnType = "date"
	Number  ColumnType = "number"
	String  ColumnType = "string"
)

// Defines values for JobStatus.
const (
	JobStatusCANCELLED JobStatus = "CANCELLED"
	JobStatusCOMPLETED JobStatus = "COMPLETED"
	JobStatusPAUSED    JobStatus = "PAUSED"
	JobStatusPENDING   JobStatus = "PENDING"
	JobStatusRUNNING   JobStatus = "RUNNING"
)

// Defines values for JobType.
const (
	Enrichment JobType = "enrichment"
	Imputation JobType = "imputation"
)

// Defines values for RowStage.
const (
	RowStageCANCELLED    RowStage = "CANCELLED"
	RowStageCOMPLETED    RowStage = "COMPLETED"
	RowStageCRAWLED      RowStage = "CRAWLED"
	RowStageDECISIONMADE RowStage = "DECISION_MADE"
	RowStageENRICHED     RowStage = "ENRICHED"
	RowStageFAILED       RowStage = "FAILED"
	RowStagePENDING      RowStage = "PENDING"
	RowStageSERPFETCHED  RowStage = "SERP_FETCHED"
)

// Defines values for SignedURLRequestContentType.
const (
	Applicationjson SignedURLRequestContentType = "application/json"
	Textcsv         SignedURLRequestContentType = "text/csv"
)

// ColumnMetadata defines model for ColumnMetadata.
type ColumnMetadata struct {
	Description *string    `json:"description"`
	JobType     JobType    `json:"job_type"`
	Name        string     `json:"name"`
	Type        ColumnType `json:"type"`
}

// ColumnType defines model for ColumnType.
type ColumnType string

// CreateCheckoutResponse defines model for CreateCheckoutResponse.
type CreateCheckoutResponse struct {
	CheckoutUrl string `json:"checkout_url"`
	SessionId   string `json:"session_id"`
}

// CreateSubscriptionRequest defines model for CreateSubscriptionRequest.
type CreateSubscriptionRequest struct {
	CancelUrl  string `json:"cancel_url"`
	SuccessUrl string `json:"success_url"`
	TierId     string `json:"tier_id"`
}

// EnrichRequest defines model for EnrichRequest.
type EnrichRequest struct {
	ColumnsMetadata      []ColumnMetadata `json:"columns_metadata"`
	KeyColumnDescription *string          `json:"key_column_description"`
	KeyColumns           *[]string        `json:"key_columns"`

	// RowLimit Maximum number of rows to process. Processes all rows if not set.
	RowLimit *int `json:"row_limit"`
}

// EnrichResponse defines model for EnrichResponse.
type EnrichResponse struct {
	JobId string `json:"job_id"`
}

// EnrichmentResult defines model for EnrichmentResult.
type EnrichmentResult struct {
	Confidence        *map[string]FieldConfidenceInfo `json:"confidence"`
	Error             *string                         `json:"error"`
	ExtractedData     map[string]interface{}          `json:"extracted_data"`
	ExtractionHistory []ExtractionHistoryEntry        `json:"extraction_history"`
	Key               string                          `json:"key"`
	Sources           []string                        `json:"sources"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// ExtractionHistoryEntry defines model for ExtractionHistoryEntry.
type ExtractionHistoryEntry struct {
	AttemptNumber int                             `json:"attempt_number"`
	Confidence    *map[string]FieldConfidenceInfo `json:"confidence"`
	ExtractedData map[string]interface{}          `json:"extracted_data"`
	Reasoning     string                          `json:"reasoning"`
	Sources       []string                        `json:"sources"`
}

// FieldConfidenceInfo defines model for FieldConfidenceInfo.
type FieldConfidenceInfo struct {
	Reason string  `json:"reason"`
	Score  float64 `json:"score"`
}

// JobProgressResponse defines model for JobProgressResponse.
type JobProgressResponse struct {
	JobId       string         `json:"job_id"`
	RowsByStage map[string]int `json:"rows_by_stage"`
	StartedAt   string         `json:"started_at"`
	Status      JobStatus      `json:"status"`
	TotalRows   int            `json:"total_rows"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JobType defines model for JobType.
type JobType string

// PaginationInfo defines model for PaginationInfo.
type PaginationInfo struct {
	HasMore bool `json:"has_more"`
	Limit   int  `json:"limit"`
	Offset  int  `json:"offset"`
	Total   int  `json:"total"`
}

// RowProgressItem defines model for RowProgressItem.
type RowProgressItem struct {
	Confidence        *map[string]FieldConfidenceInfo `json:"confidence"`
	Error             *string                         `json:"error"`
	ExtractedData     *map[string]interface{}         `json:"extracted_data"`
	ExtractionHistory []ExtractionHistoryEntry        `json:"extraction_history"`
	Key               string                          `json:"key"`
	Sources           *[]string                       `json:"sources"`
	Stage             RowStage                        `json:"stage"`
	UpdatedAt         time.Time                       `json:"updated_at"`
}

// RowStage defines model for RowStage.
type RowStage string

// RowsProgressResponse defines model for RowsProgressResponse.
type RowsProgressResponse struct {
	Pagination PaginationInfo    `json:"pagination"`
	Rows       []RowProgressItem `json:"rows"`
}

// SelectKeyRequest defines model for SelectKeyRequest.
type SelectKeyRequest struct {
	ColumnsMetadata *[]ColumnMetadata  `json:"columns_metadata"`
	SourceId        openapi_types.UUID `json:"source_id"`
}

// SelectKeyResponse defines model for SelectKeyResponse.
type SelectKeyResponse struct {
	AllKeys     []string `json:"all_keys"`
	Reasoning   string   `json:"reasoning"`
	SelectedKey string   `json:"selected_key"`
}

// SignedURLRequest defines model for SignedURLRequest.
type SignedURLRequest struct {
	ContentType SignedURLRequestContentType `json:"contentType"`

	// Headers CSV column headers, used to generate an AI name for the source
	Headers *[]string `json:"headers,omitempty"`
	Length  int       `json:"length"`
}

// SignedURLRequestContentType defines model for SignedURLRequest.ContentType.
type SignedURLRequestContentType string

// SignedURLResponse defines model for SignedURLResponse.
type SignedURLResponse struct {
	SourceId openapi_types.UUID `json:"sourceId"`
	Url      string             `json:"url"`
}

// SourceDetail defines model for SourceDetail.
type SourceDetail struct {
	CreatedAt time.Time          `json:"created_at"`
	Jobs      []SourceJobSummary `json:"jobs"`
	SourceId  openapi_types.UUID `json:"source_id"`
	Type      string             `json:"type"`
}

// SourceJobSummary defines model for SourceJobSummary.
type SourceJobSummary struct {
	ColumnsMetadata      *[]ColumnMetadata `json:"columns_metadata"`
	CreatedAt            time.Time         `json:"created_at"`
	JobId                string            `json:"job_id"`
	KeyColumnDescription *string           `json:"key_column_description"`
	KeyColumns           *[]string         `json:"key_columns"`
	StartedAt            *time.Time        `json:"started_at"`
	Status               JobStatus         `json:"status"`
	TotalRows            int               `json:"total_rows"`
}

// SourceListResponse defines model for SourceListResponse.
type SourceListResponse struct {
	Sources    []SourceSummary `json:"sources"`
	TotalCount int             `json:"total_count"`
}

// SourceSummary defines model for SourceSummary.
type SourceSummary struct {
	CreatedAt       time.Time          `json:"created_at"`
	JobCount        int                `json:"job_count"`
	LatestJobStatus *JobStatus         `json:"latest_job_status,omitempty"`
	Name            *string            `json:"name"`
	SourceId        openapi_types.UUID `json:"source_id"`
	Type            string             `json:"type"`
}

// SubscriptionStatusResponse defines model for SubscriptionStatusResponse.
type SubscriptionStatusResponse struct {
	CancelAtPeriodEnd  bool       `json:"cancel_at_period_end"`
	CurrentPeriodEnd   *time.Time `json:"current_period_end"`
	CurrentPeriodStart *time.Time `json:"current_period_start"`
	Tier               *string    `json:"tier"`
	TokensIncluded     int64      `json:"tokens_included"`
	TokensUsed         int64      `json:"tokens_used"`
}

// TierResponse defines model for TierResponse.
type TierResponse struct {
	DisplayName              string `json:"display_name"`
	Id                       string `json:"id"`
	IncludedTokens           int64  `json:"included_tokens"`
	MonthlyPriceCents        int64  `json:"monthly_price_cents"`
	OveragePriceCentsDecimal string `json:"overage_price_cents_decimal"`
}

// UpgradeSubscriptionRequest defines model for UpgradeSubscriptionRequest.
type UpgradeSubscriptionRequest struct {
	TierId string `json:"tier_id"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

// GetJobResultsParams defines parameters for GetJobResults.
type GetJobResultsParams struct {
	Start *int `form:"start,omitempty" json:"start,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetRowsProgressParams defines parameters for GetRowsProgress.
type GetRowsProgressParams struct {
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Stage  *string `form:"stage,omitempty" json:"stage,omitempty"`
	Sort   *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePortalSessionParams defines parameters for CreatePortalSession.
type CreatePortalSessionParams struct {
	ReturnUrl string `form:"return_url" json:"return_url"`
}

// HandleStripeWebhookParams defines parameters for HandleStripeWebhook.
type HandleStripeWebhookParams struct {
	StripeSignature string `json:"Stripe-Signature"`
}

// UploadFileForEnrichmentJSONRequestBody defines body for UploadFileForEnrichment for application/json ContentType.
type UploadFileForEnrichmentJSONRequestBody = SignedURLRequest

// SelectKeyJSONRequestBody defines body for SelectKey for application/json ContentType.
type SelectKeyJSONRequestBody = SelectKeyRequest

// EnrichSourceJSONRequestBody defines body for EnrichSource for application/json ContentType.
type EnrichSourceJSONRequestBody = EnrichRequest

// CreateSubscriptionCheckoutJSONRequestBody defines body for CreateSubscriptionCheckout for application/json ContentType.
type CreateSubscriptionCheckoutJSONRequestBody = CreateSubscriptionRequest

// UpgradeSubscriptionJSONRequestBody defines body for UpgradeSubscription for application/json ContentType.
type UpgradeSubscriptionJSONRequestBody = UpgradeSubscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a pending enrichment job and get a signed upload URL
	// (POST /enrichment-signed-url)
	UploadFileForEnrichment(w http.ResponseWriter, r *http.Request)
	// Cancel a running enrichment job
	// (POST /jobs/{jobID}/cancel)
	CancelJob(w http.ResponseWriter, r *http.Request, jobID string)
	// Get progress summary for a job
	// (GET /jobs/{jobID}/progress)
	GetJobProgress(w http.ResponseWriter, r *http.Request, jobID string)
	// Get enrichment results for a job
	// (GET /jobs/{jobID}/results)
	GetJobResults(w http.ResponseWriter, r *http.Request, jobID string, params GetJobResultsParams)
	// Get per-row progress for a job
	// (GET /jobs/{jobID}/rows)
	GetRowsProgress(w http.ResponseWriter, r *http.Request, jobID string, params GetRowsProgressParams)
	// Get the current authenticated user's profile
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Use AI to select the best key column from a source's CSV
	// (POST /select-key)
	SelectKey(w http.ResponseWriter, r *http.Request)
	// List sources for the authenticated user
	// (GET /sources)
	ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams)
	// Get source details with all enrichment runs
	// (GET /sources/{sourceID})
	GetSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID)
	// Get the raw CSV data for a source
	// (GET /sources/{sourceID}/data)
	GetSourceData(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID)
	// Start a new enrichment run for a source
	// (POST /sources/{sourceID}/enrich)
	EnrichSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID)
	// Create a Stripe checkout session for a subscription
	// (POST /subscribe)
	CreateSubscriptionCheckout(w http.ResponseWriter, r *http.Request)
	// Get the current user's subscription status
	// (GET /subscription)
	GetSubscriptionStatus(w http.ResponseWriter, r *http.Request)
	// Cancel the current user's subscription
	// (POST /subscription/cancel)
	CancelSubscription(w http.ResponseWriter, r *http.Request)
	// Create a Stripe customer portal session
	// (POST /subscription/portal)
	CreatePortalSession(w http.ResponseWriter, r *http.Request, params CreatePortalSessionParams)
	// Upgrade the current user's subscription to a higher tier
	// (POST /subscription/upgrade)
	UpgradeSubscription(w http.ResponseWriter, r *http.Request)
	// List available subscription tiers
	// (GET /tiers)
	ListTiers(w http.ResponseWriter, r *http.Request)
	// Handle Stripe webhook events
	// (POST /webhooks/stripe)
	HandleStripeWebhook(w http.ResponseWriter, r *http.Request, params HandleStripeWebhookParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadFileForEnrichment operation middleware
func (siw *ServerInterfaceWrapper) UploadFileForEnrichment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadFileForEnrichment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CancelJob operation middleware
func (siw *ServerInterfaceWrapper) CancelJob(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelJob(w, r, jobID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetJobProgress operation middleware
func (siw *ServerInterfaceWrapper) GetJobProgress(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobProgress(w, r, jobID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetJobResults operation middleware
func (siw *ServerInterfaceWrapper) GetJobResults(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJobResultsParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameter("form", true, false, "start", r.URL.Query(), &params.Start)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobResults(w, r, jobID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRowsProgress operation middleware
func (siw *ServerInterfaceWrapper) GetRowsProgress(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "jobID" -------------
	var jobID string

	err = runtime.BindStyledParameterWithOptions("simple", "jobID", mux.Vars(r)["jobID"], &jobID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRowsProgressParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "stage" -------------

	err = runtime.BindQueryParameter("form", true, false, "stage", r.URL.Query(), &params.Stage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRowsProgress(w, r, jobID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SelectKey operation middleware
func (siw *ServerInterfaceWrapper) SelectKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListSources operation middleware
func (siw *ServerInterfaceWrapper) ListSources(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSourcesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "sourceID" -------------
	var sourceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sourceID", mux.Vars(r)["sourceID"], &sourceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, sourceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSourceData operation middleware
func (siw *ServerInterfaceWrapper) GetSourceData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "sourceID" -------------
	var sourceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sourceID", mux.Vars(r)["sourceID"], &sourceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSourceData(w, r, sourceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// EnrichSource operation middleware
func (siw *ServerInterfaceWrapper) EnrichSource(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "sourceID" -------------
	var sourceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sourceID", mux.Vars(r)["sourceID"], &sourceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrichSource(w, r, sourceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateSubscriptionCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscriptionCheckout(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscriptionCheckout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSubscriptionStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSubscriptionStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscriptionStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CancelSubscription operation middleware
func (siw *ServerInterfaceWrapper) CancelSubscription(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreatePortalSession operation middleware
func (siw *ServerInterfaceWrapper) CreatePortalSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePortalSessionParams

	// ------------- Required query parameter "return_url" -------------

	if paramValue := r.URL.Query().Get("return_url"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "return_url"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "return_url", r.URL.Query(), &params.ReturnUrl)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "return_url", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePortalSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpgradeSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpgradeSubscription(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpgradeSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListTiers operation middleware
func (siw *ServerInterfaceWrapper) ListTiers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTiers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// HandleStripeWebhook operation middleware
func (siw *ServerInterfaceWrapper) HandleStripeWebhook(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleStripeWebhookParams

	headers := r.Header

	// ------------- Required header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Stripe-Signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Stripe-Signature", Err: err})
			return
		}

		params.StripeSignature = StripeSignature

	} else {
		err = fmt.Errorf("Header parameter Stripe-Signature is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Stripe-Signature", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleStripeWebhook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/enrichment-signed-url", wrapper.UploadFileForEnrichment).Methods("POST")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/cancel", wrapper.CancelJob).Methods("POST")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/progress", wrapper.GetJobProgress).Methods("GET")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/results", wrapper.GetJobResults).Methods("GET")

	r.HandleFunc(options.BaseURL+"/jobs/{jobID}/rows", wrapper.GetRowsProgress).Methods("GET")

	r.HandleFunc(options.BaseURL+"/me", wrapper.GetMe).Methods("GET")

	r.HandleFunc(options.BaseURL+"/select-key", wrapper.SelectKey).Methods("POST")

	r.HandleFunc(options.BaseURL+"/sources", wrapper.ListSources).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sources/{sourceID}", wrapper.GetSource).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sources/{sourceID}/data", wrapper.GetSourceData).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sources/{sourceID}/enrich", wrapper.EnrichSource).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscribe", wrapper.CreateSubscriptionCheckout).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscription", wrapper.GetSubscriptionStatus).Methods("GET")

	r.HandleFunc(options.BaseURL+"/subscription/cancel", wrapper.CancelSubscription).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscription/portal", wrapper.CreatePortalSession).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscription/upgrade", wrapper.UpgradeSubscription).Methods("POST")

	r.HandleFunc(options.BaseURL+"/tiers", wrapper.ListTiers).Methods("GET")

	r.HandleFunc(options.BaseURL+"/webhooks/stripe", wrapper.HandleStripeWebhook).Methods("POST")

	return r
}

type UploadFileForEnrichmentRequestObject struct {
	Body *UploadFileForEnrichmentJSONRequestBody
}

type UploadFileForEnrichmentResponseObject interface {
	VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error
}

type UploadFileForEnrichment200JSONResponse SignedURLResponse

func (response UploadFileForEnrichment200JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UploadFileForEnrichment400JSONResponse ErrorResponse

func (response UploadFileForEnrichment400JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadFileForEnrichment401JSONResponse ErrorResponse

func (response UploadFileForEnrichment401JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UploadFileForEnrichment500JSONResponse ErrorResponse

func (response UploadFileForEnrichment500JSONResponse) VisitUploadFileForEnrichmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CancelJobRequestObject struct {
	JobID string `json:"jobID"`
}

type CancelJobResponseObject interface {
	VisitCancelJobResponse(w http.ResponseWriter) error
}

type CancelJob200JSONResponse struct {
	Message string `json:"message"`
}

func (response CancelJob200JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelJob404JSONResponse ErrorResponse

func (response CancelJob404JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelJob500JSONResponse ErrorResponse

func (response CancelJob500JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobProgressRequestObject struct {
	JobID string `json:"jobID"`
}

type GetJobProgressResponseObject interface {
	VisitGetJobProgressResponse(w http.ResponseWriter) error
}

type GetJobProgress200JSONResponse JobProgressResponse

func (response GetJobProgress200JSONResponse) VisitGetJobProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobProgress404JSONResponse ErrorResponse

func (response GetJobProgress404JSONResponse) VisitGetJobProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobResultsRequestObject struct {
	JobID  string `json:"jobID"`
	Params GetJobResultsParams
}

type GetJobResultsResponseObject interface {
	VisitGetJobResultsResponse(w http.ResponseWriter) error
}

type GetJobResults200JSONResponse []EnrichmentResult

func (response GetJobResults200JSONResponse) VisitGetJobResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobResults500JSONResponse ErrorResponse

func (response GetJobResults500JSONResponse) VisitGetJobResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRowsProgressRequestObject struct {
	JobID  string `json:"jobID"`
	Params GetRowsProgressParams
}

type GetRowsProgressResponseObject interface {
	VisitGetRowsProgressResponse(w http.ResponseWriter) error
}

type GetRowsProgress200JSONResponse RowsProgressResponse

func (response GetRowsProgress200JSONResponse) VisitGetRowsProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRowsProgress400JSONResponse ErrorResponse

func (response GetRowsProgress400JSONResponse) VisitGetRowsProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRowsProgress500JSONResponse ErrorResponse

func (response GetRowsProgress500JSONResponse) VisitGetRowsProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse UserResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401JSONResponse ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SelectKeyRequestObject struct {
	Body *SelectKeyJSONRequestBody
}

type SelectKeyResponseObject interface {
	VisitSelectKeyResponse(w http.ResponseWriter) error
}

type SelectKey200JSONResponse SelectKeyResponse

func (response SelectKey200JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey400JSONResponse ErrorResponse

func (response SelectKey400JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey401JSONResponse ErrorResponse

func (response SelectKey401JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey403JSONResponse ErrorResponse

func (response SelectKey403JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey404JSONResponse ErrorResponse

func (response SelectKey404JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SelectKey500JSONResponse ErrorResponse

func (response SelectKey500JSONResponse) VisitSelectKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListSourcesRequestObject struct {
	Params ListSourcesParams
}

type ListSourcesResponseObject interface {
	VisitListSourcesResponse(w http.ResponseWriter) error
}

type ListSources200JSONResponse SourceListResponse

func (response ListSources200JSONResponse) VisitListSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSources401JSONResponse ErrorResponse

func (response ListSources401JSONResponse) VisitListSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListSources500JSONResponse ErrorResponse

func (response ListSources500JSONResponse) VisitListSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRequestObject struct {
	SourceID openapi_types.UUID `json:"sourceID"`
}

type GetSourceResponseObject interface {
	VisitGetSourceResponse(w http.ResponseWriter) error
}

type GetSource200JSONResponse SourceDetail

func (response GetSource200JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSource401JSONResponse ErrorResponse

func (response GetSource401JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSource403JSONResponse ErrorResponse

func (response GetSource403JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSource404JSONResponse ErrorResponse

func (response GetSource404JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSource500JSONResponse ErrorResponse

func (response GetSource500JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceDataRequestObject struct {
	SourceID openapi_types.UUID `json:"sourceID"`
}

type GetSourceDataResponseObject interface {
	VisitGetSourceDataResponse(w http.ResponseWriter) error
}

type GetSourceData200JSONResponse struct {
	Headers []string   `json:"headers"`
	Rows    [][]string `json:"rows"`
}

func (response GetSourceData200JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData401JSONResponse ErrorResponse

func (response GetSourceData401JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData403JSONResponse ErrorResponse

func (response GetSourceData403JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData404JSONResponse ErrorResponse

func (response GetSourceData404JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceData500JSONResponse ErrorResponse

func (response GetSourceData500JSONResponse) VisitGetSourceDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSourceRequestObject struct {
	SourceID openapi_types.UUID `json:"sourceID"`
	Body     *EnrichSourceJSONRequestBody
}

type EnrichSourceResponseObject interface {
	VisitEnrichSourceResponse(w http.ResponseWriter) error
}

type EnrichSource200JSONResponse EnrichResponse

func (response EnrichSource200JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource400JSONResponse ErrorResponse

func (response EnrichSource400JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource401JSONResponse ErrorResponse

func (response EnrichSource401JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource402JSONResponse ErrorResponse

func (response EnrichSource402JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(402)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource403JSONResponse ErrorResponse

func (response EnrichSource403JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource404JSONResponse ErrorResponse

func (response EnrichSource404JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type EnrichSource500JSONResponse ErrorResponse

func (response EnrichSource500JSONResponse) VisitEnrichSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionCheckoutRequestObject struct {
	Body *CreateSubscriptionCheckoutJSONRequestBody
}

type CreateSubscriptionCheckoutResponseObject interface {
	VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error
}

type CreateSubscriptionCheckout200JSONResponse CreateCheckoutResponse

func (response CreateSubscriptionCheckout200JSONResponse) VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionCheckout400JSONResponse ErrorResponse

func (response CreateSubscriptionCheckout400JSONResponse) VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionCheckout500JSONResponse ErrorResponse

func (response CreateSubscriptionCheckout500JSONResponse) VisitCreateSubscriptionCheckoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionStatusRequestObject struct {
}

type GetSubscriptionStatusResponseObject interface {
	VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error
}

type GetSubscriptionStatus200JSONResponse SubscriptionStatusResponse

func (response GetSubscriptionStatus200JSONResponse) VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionStatus400JSONResponse ErrorResponse

func (response GetSubscriptionStatus400JSONResponse) VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscriptionRequestObject struct {
}

type CancelSubscriptionResponseObject interface {
	VisitCancelSubscriptionResponse(w http.ResponseWriter) error
}

type CancelSubscription200JSONResponse struct {
	Message string `json:"message"`
}

func (response CancelSubscription200JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscription400JSONResponse ErrorResponse

func (response CancelSubscription400JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscription500JSONResponse ErrorResponse

func (response CancelSubscription500JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePortalSessionRequestObject struct {
	Params CreatePortalSessionParams
}

type CreatePortalSessionResponseObject interface {
	VisitCreatePortalSessionResponse(w http.ResponseWriter) error
}

type CreatePortalSession200JSONResponse struct {
	Url string `json:"url"`
}

func (response CreatePortalSession200JSONResponse) VisitCreatePortalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePortalSession400JSONResponse ErrorResponse

func (response CreatePortalSession400JSONResponse) VisitCreatePortalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePortalSession500JSONResponse ErrorResponse

func (response CreatePortalSession500JSONResponse) VisitCreatePortalSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeSubscriptionRequestObject struct {
	Body *UpgradeSubscriptionJSONRequestBody
}

type UpgradeSubscriptionResponseObject interface {
	VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error
}

type UpgradeSubscription200JSONResponse struct {
	Message string `json:"message"`
}

func (response UpgradeSubscription200JSONResponse) VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeSubscription400JSONResponse ErrorResponse

func (response UpgradeSubscription400JSONResponse) VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeSubscription500JSONResponse ErrorResponse

func (response UpgradeSubscription500JSONResponse) VisitUpgradeSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTiersRequestObject struct {
}

type ListTiersResponseObject interface {
	VisitListTiersResponse(w http.ResponseWriter) error
}

type ListTiers200JSONResponse []TierResponse

func (response ListTiers200JSONResponse) VisitListTiersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleStripeWebhookRequestObject struct {
	Params HandleStripeWebhookParams
	Body   io.Reader
}

type HandleStripeWebhookResponseObject interface {
	VisitHandleStripeWebhookResponse(w http.ResponseWriter) error
}

type HandleStripeWebhook200Response struct {
}

func (response HandleStripeWebhook200Response) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type HandleStripeWebhook400JSONResponse ErrorResponse

func (response HandleStripeWebhook400JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleStripeWebhook401JSONResponse ErrorResponse

func (response HandleStripeWebhook401JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type HandleStripeWebhook500JSONResponse ErrorResponse

func (response HandleStripeWebhook500JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a pending enrichment job and get a signed upload URL
	// (POST /enrichment-signed-url)
	UploadFileForEnrichment(ctx context.Context, request UploadFileForEnrichmentRequestObject) (UploadFileForEnrichmentResponseObject, error)
	// Cancel a running enrichment job
	// (POST /jobs/{jobID}/cancel)
	CancelJob(ctx context.Context, request CancelJobRequestObject) (CancelJobResponseObject, error)
	// Get progress summary for a job
	// (GET /jobs/{jobID}/progress)
	GetJobProgress(ctx context.Context, request GetJobProgressRequestObject) (GetJobProgressResponseObject, error)
	// Get enrichment results for a job
	// (GET /jobs/{jobID}/results)
	GetJobResults(ctx context.Context, request GetJobResultsRequestObject) (GetJobResultsResponseObject, error)
	// Get per-row progress for a job
	// (GET /jobs/{jobID}/rows)
	GetRowsProgress(ctx context.Context, request GetRowsProgressRequestObject) (GetRowsProgressResponseObject, error)
	// Get the current authenticated user's profile
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Use AI to select the best key column from a source's CSV
	// (POST /select-key)
	SelectKey(ctx context.Context, request SelectKeyRequestObject) (SelectKeyResponseObject, error)
	// List sources for the authenticated user
	// (GET /sources)
	ListSources(ctx context.Context, request ListSourcesRequestObject) (ListSourcesResponseObject, error)
	// Get source details with all enrichment runs
	// (GET /sources/{sourceID})
	GetSource(ctx context.Context, request GetSourceRequestObject) (GetSourceResponseObject, error)
	// Get the raw CSV data for a source
	// (GET /sources/{sourceID}/data)
	GetSourceData(ctx context.Context, request GetSourceDataRequestObject) (GetSourceDataResponseObject, error)
	// Start a new enrichment run for a source
	// (POST /sources/{sourceID}/enrich)
	EnrichSource(ctx context.Context, request EnrichSourceRequestObject) (EnrichSourceResponseObject, error)
	// Create a Stripe checkout session for a subscription
	// (POST /subscribe)
	CreateSubscriptionCheckout(ctx context.Context, request CreateSubscriptionCheckoutRequestObject) (CreateSubscriptionCheckoutResponseObject, error)
	// Get the current user's subscription status
	// (GET /subscription)
	GetSubscriptionStatus(ctx context.Context, request GetSubscriptionStatusRequestObject) (GetSubscriptionStatusResponseObject, error)
	// Cancel the current user's subscription
	// (POST /subscription/cancel)
	CancelSubscription(ctx context.Context, request CancelSubscriptionRequestObject) (CancelSubscriptionResponseObject, error)
	// Create a Stripe customer portal session
	// (POST /subscription/portal)
	CreatePortalSession(ctx context.Context, request CreatePortalSessionRequestObject) (CreatePortalSessionResponseObject, error)
	// Upgrade the current user's subscription to a higher tier
	// (POST /subscription/upgrade)
	UpgradeSubscription(ctx context.Context, request UpgradeSubscriptionRequestObject) (UpgradeSubscriptionResponseObject, error)
	// List available subscription tiers
	// (GET /tiers)
	ListTiers(ctx context.Context, request ListTiersRequestObject) (ListTiersResponseObject, error)
	// Handle Stripe webhook events
	// (POST /webhooks/stripe)
	HandleStripeWebhook(ctx context.Context, request HandleStripeWebhookRequestObject) (HandleStripeWebhookResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// UploadFileForEnrichment operation middleware
func (sh *strictHandler) UploadFileForEnrichment(w http.ResponseWriter, r *http.Request) {
	var request UploadFileForEnrichmentRequestObject

	var body UploadFileForEnrichmentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadFileForEnrichment(ctx, request.(UploadFileForEnrichmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadFileForEnrichment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadFileForEnrichmentResponseObject); ok {
		if err := validResponse.VisitUploadFileForEnrichmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelJob operation middleware
func (sh *strictHandler) CancelJob(w http.ResponseWriter, r *http.Request, jobID string) {
	var request CancelJobRequestObject

	request.JobID = jobID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelJob(ctx, request.(CancelJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelJobResponseObject); ok {
		if err := validResponse.VisitCancelJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobProgress operation middleware
func (sh *strictHandler) GetJobProgress(w http.ResponseWriter, r *http.Request, jobID string) {
	var request GetJobProgressRequestObject

	request.JobID = jobID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobProgress(ctx, request.(GetJobProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobProgress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobProgressResponseObject); ok {
		if err := validResponse.VisitGetJobProgressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobResults operation middleware
func (sh *strictHandler) GetJobResults(w http.ResponseWriter, r *http.Request, jobID string, params GetJobResultsParams) {
	var request GetJobResultsRequestObject

	request.JobID = jobID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobResults(ctx, request.(GetJobResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResultsResponseObject); ok {
		if err := validResponse.VisitGetJobResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRowsProgress operation middleware
func (sh *strictHandler) GetRowsProgress(w http.ResponseWriter, r *http.Request, jobID string, params GetRowsProgressParams) {
	var request GetRowsProgressRequestObject

	request.JobID = jobID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRowsProgress(ctx, request.(GetRowsProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRowsProgress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRowsProgressResponseObject); ok {
		if err := validResponse.VisitGetRowsProgressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SelectKey operation middleware
func (sh *strictHandler) SelectKey(w http.ResponseWriter, r *http.Request) {
	var request SelectKeyRequestObject

	var body SelectKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SelectKey(ctx, request.(SelectKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SelectKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SelectKeyResponseObject); ok {
		if err := validResponse.VisitSelectKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSources operation middleware
func (sh *strictHandler) ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams) {
	var request ListSourcesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSources(ctx, request.(ListSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSourcesResponseObject); ok {
		if err := validResponse.VisitListSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSource operation middleware
func (sh *strictHandler) GetSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID) {
	var request GetSourceRequestObject

	request.SourceID = sourceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSource(ctx, request.(GetSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceResponseObject); ok {
		if err := validResponse.VisitGetSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSourceData operation middleware
func (sh *strictHandler) GetSourceData(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID) {
	var request GetSourceDataRequestObject

	request.SourceID = sourceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSourceData(ctx, request.(GetSourceDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSourceData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceDataResponseObject); ok {
		if err := validResponse.VisitGetSourceDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrichSource operation middleware
func (sh *strictHandler) EnrichSource(w http.ResponseWriter, r *http.Request, sourceID openapi_types.UUID) {
	var request EnrichSourceRequestObject

	request.SourceID = sourceID

	var body EnrichSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnrichSource(ctx, request.(EnrichSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrichSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnrichSourceResponseObject); ok {
		if err := validResponse.VisitEnrichSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSubscriptionCheckout operation middleware
func (sh *strictHandler) CreateSubscriptionCheckout(w http.ResponseWriter, r *http.Request) {
	var request CreateSubscriptionCheckoutRequestObject

	var body CreateSubscriptionCheckoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscriptionCheckout(ctx, request.(CreateSubscriptionCheckoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscriptionCheckout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubscriptionCheckoutResponseObject); ok {
		if err := validResponse.VisitCreateSubscriptionCheckoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscriptionStatus operation middleware
func (sh *strictHandler) GetSubscriptionStatus(w http.ResponseWriter, r *http.Request) {
	var request GetSubscriptionStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscriptionStatus(ctx, request.(GetSubscriptionStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscriptionStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionStatusResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelSubscription operation middleware
func (sh *strictHandler) CancelSubscription(w http.ResponseWriter, r *http.Request) {
	var request CancelSubscriptionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelSubscription(ctx, request.(CancelSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelSubscriptionResponseObject); ok {
		if err := validResponse.VisitCancelSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePortalSession operation middleware
func (sh *strictHandler) CreatePortalSession(w http.ResponseWriter, r *http.Request, params CreatePortalSessionParams) {
	var request CreatePortalSessionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePortalSession(ctx, request.(CreatePortalSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePortalSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePortalSessionResponseObject); ok {
		if err := validResponse.VisitCreatePortalSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpgradeSubscription operation middleware
func (sh *strictHandler) UpgradeSubscription(w http.ResponseWriter, r *http.Request) {
	var request UpgradeSubscriptionRequestObject

	var body UpgradeSubscriptionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpgradeSubscription(ctx, request.(UpgradeSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpgradeSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpgradeSubscriptionResponseObject); ok {
		if err := validResponse.VisitUpgradeSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTiers operation middleware
func (sh *strictHandler) ListTiers(w http.ResponseWriter, r *http.Request) {
	var request ListTiersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTiers(ctx, request.(ListTiersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTiers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTiersResponseObject); ok {
		if err := validResponse.VisitListTiersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleStripeWebhook operation middleware
func (sh *strictHandler) HandleStripeWebhook(w http.ResponseWriter, r *http.Request, params HandleStripeWebhookParams) {
	var request HandleStripeWebhookRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleStripeWebhook(ctx, request.(HandleStripeWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleStripeWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleStripeWebhookResponseObject); ok {
		if err := validResponse.VisitHandleStripeWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcXXPbttL+Kxi870xvmMhp03PhO9eWW+U4rkeK24tMhgORKwkJCbAAaFfHo/9+Bh/8",
	"Bik6jWSfie9sEVgsdp9d7GKXfMARTzPOgCmJTx+wjDaQEvPnOU/ylL0HRWKiiP4lEzwDoSiY5zHISNBM",
	"Uc70vyxPErJMAJ8qkUOA1TYDfIqlEpSt8S7An/kytD8+4P8XsMKn+P8m1eoTt/TkHV9+0MN2AWYkNcM7",
	"tMbQsfxbUrsAC/grpwJifPrR0nVUaox9Krnmy88QKb1SjcrpAwaWp5qA4yTALE+XIHCAl5wnQBgOcExU",
	"nVTF9LkAouB8A9EXnqs5yIwzCV3BRm5EmIvEu3sJUlLOQhp7Hre22iDWmOrdrWFxkS9L1c7hrxyk8nBJ",
	"WARJP495FIGUvc8VBTFqA8XAJsmgvr5vJ1MmaLTp596oVYZpDd5UQSrHoaq0il2AU8pmduabkg8iBNnq",
	"h19gG9q1wsfaSzVVNrjrDOyhVPIg+H2Y0JSqjtXi9+RvmuYpsjBGfIUEv5dIcZQJroX9Gt3YP0AikiT2",
	"MV0hxhWSoF5js39Nw2y/hxXKFKxBdMHZ1sKQJvvMRZvvGCC5cf1LpMC0VeaJFy9sRWNgkWGAxDHVEiTJ",
	"TWPUEHAuKSTxeUlmxlZ8QHkVbyAEF6MAA38rQSIFcVgg2s9n30J2uvYOGyoVF9vRRjEtp/5mZ06ZEtvK",
	"UTfswe8ueC4i2AP0JrGWejXljgwqwt79ebGg5d2PthSkJGvYD7dioHcNv7w6ixGlIM1U6E6Zas3SoIKn",
	"ROY/w5sAIjnTojsMIFrCG8RGxYtPXT4BdXRlSfj3EnFhtLPiIiUKn+KY51qy5VqOx/YW7MSCPS9v7/jy",
	"RvC1ACm/wkWaw0GGy20olUN1H4K6yOvwIhURWrxE+cWgiMrliPBvYQfqJbgiSah59LHgd/CNWe0NNpgs",
	"WeoR7KJkuIj7bqbXF7PrX3GA57fX1/avm7PbxfQCB/j87Pp8enVl//79/c3V9MP0whsJFiFujTKURxAO",
	"ME2zXBFzRvum35A1ZeaxH4obIsPUQc5NLsLTXYDLUKCrUb5aSeh5ZoQ6Qgt2XEmrWC+ouPJJe87vCxjr",
	"YOp7OIDH+tdnfCDvizxLpzLE65zfL8y4XYDzTGdPhQep3CVR8ErRtOYxe05dGwUUtl4jN/r8L9nxmv1i",
	"Or8JL6cfzn8zZn4xPZ8tZr9fh+/PLqba7Odnf1oHML2ez9ygyhcE+PJsdtVyFj4Ln/N7ud+tZ6Uf2Cfj",
	"lsdwfn80nNrWue/oda63xp9P0gtIIFL/hu0xsrS9UDV4d6dkCbw8twfKIOaqqXt22adHkiThF9g+KtjZ",
	"Gz+ZZSEO/Qbe3kJ9dFAxtC8yWtA1g/h2fjWgQqaAqfZxp+BvNYnknV4syxIaGZhMPsueI28DJAbRvXfC",
	"54s/kIUJcmMClEuIdQ67BgaCKECEobMZYiQFtOICqQ0gqzR91o4WeAJsrTYmCailvHtT3Gr/JYk9ouzD",
	"ieV5NgaiAfZfvLS4c5dCBV0vX+bhBShCE496zYXRYxy2uW8b73rs8joYy9OU+M+wx9hudXc41qjLe8La",
	"Xt0m+uVVY/gpvdpXqqcvWXgOt1nNJMO7pb3MHC0TcQu1UpKaVvoRdEWl2ucKHmtGAzZkGYx4ztSIDVaZ",
	"c31e/2b6beErAdrLaIATokCqUI/6Cj0XJYf9GHoapzMk6tq1vd3QQI3B3p4TFWYgKI9DYLE/XYxyIYC1",
	"x32d3bVoGVP+emqKwri8TPEvwGRIWZTkMTT5p0z96y0OvAmvmaWDiVEzOnlwNb3LQuDXgE+tHygM3EfG",
	"VGYJ2Ya9pbIeV15wElrORsok5Uxtkm2YCRpBGBVVwxEz+R0Isob6zDCGiKZkRJhiDKKxUz8r3W0NL+wT",
	"9222FiQeVwN7dBHLu6Ac0i+kLu7qaHBFhVT9ek9I/9MWdzVK9XmBW7zLtMkvolxQtV1oJ2pZ/QWIAHGW",
	"2xh5af67LJDx7s8P+jw0o7WDMU8rpGyUyvBuZ4Bpr7SaYf5ZmiVwQRRB1UUZOruZaQpUaduvDbG/34GQ",
	"dvKb1yevTwwIM2Ako/gU//T65PVPJkVVG8P8pKL7SppQ/JWLoDNuVa+1YlPoGJ/i2yzhJL6kCVxyMa1f",
	"3gmLll94vK0lQCbPa2c6ZcF97/HdzrN2TR1qx2d+sDAyO/rx5OQQ6zugGgaaOrKD0O38qsy8Yi31t9+Q",
	"kWZ1xsPELyRGohCSXvvN8da+ZSRXGy7of+zGfz7mxmdMgWAkQRLEHQhkry2NqRbBlyvvI4IyYDFl67ox",
	"feZLRFiM1qAQQdYEUG5QrlWqDY2spYtuJf6kKU/0n5OHz3w5u9hN7InWbzLn5vk7vjR2J0gKyqT0Hx8w",
	"1TvQtoiLCAwborgN8qAmrrZT+/QPDeCbF/q6SnrHl8iKKSls4+3xIKJXZ1yhFc/ZMwWokQ0iSOSMdQE6",
	"AoSZu6fU7K7Bg8JfQdVqZs8UinvSlc7VcI+yS2E8MdIaOv4VVMkYcj+bazkyUsXC9Gjs0/DcjTqMggNH",
	"568cxLYiZDOa+sQYVsR0lJz4MgY/laJiNpLKPwXbuIpSu0WmWwPooKCagwqdPUenowEJHVYfB0l3L9SH",
	"x3o957iILMuwB4PkzycBTm0fGT59c/IIomVJvksUkyTxFV56CPE+q6uVAM2VpYfmIX21t47ngemc37ec",
	"9dOFzM/SPjMQr0RNSPus06a9feb43jbVHEjpjYTelyZIEHojK5rAE+coHTmrDSB3S4f0QGBKM6JTAQni",
	"B1nyXUldPyjEbuuIr1zN0Z8GlAXRQ+XK7bLysXPlTsHXlyu7givSovqec+S3Jz8db/FLLpY0joEdPSC2",
	"ZZBnnn3dSkBnM6Q4snZsvMESpNIoLarsK8FTRFz9/AeJzhd/+F1wrUTl9cNXVKpFWUfyhURPEsp88/B6",
	"f1muUerz6E4/R3yFCom+3Gu1gGsE5KRTdnh0j68aTgtRNqA6eXCdEBe7oehhUbSO7A/jC3qDkfy+bqPD",
	"A9B1d/T7rdgNeDksXg6LWrQo6+iQ6J6qjXlLqJ5N56YKN9buJkVDzLDxXdgG/v8RA2x1Z1etbI9o9mu3",
	"a46fOtipWTDjVhhzhz0n9/rQR0UP0otHePEIjfxR1ADi8vSy23K0H7AupD+LtHeLT3IUf/uUtfmy6pHz",
	"1db7lcP3uK777jtPWX883uI3ZOtupR0eXpzes3J6C20QiCAG962wZ6Trs31GSxiom3deyi++IXCgG7T+",
	"rwAc2TX1fDHBo6piDHIfOECub/LlMr2vBWShBM0ARW3BOdTWlF/D7pImiXkXpI7dsgm8N2bvNKYe8vp9",
	"oA3W52Rqo5Es24CPihlTEBgql9dv5d09vPTwPUZPI7t0Fk39P/e+moYWWw02R1TkNUckUvQOmvbzjDtt",
	"9iBrHKQyLty7wUMH2I0ZtbBuZtyNrwCVC+Y++PJUjWCjX6QaA1QrhNLZ3s6vntjbIC5QSqWkbF0eCblU",
	"PLVt28///HLMoqwh2XHAzW2v91CXb6cZ/EAx10Db+QGCrmO7ZCfol3CsU3Kzgtl7wiuOCNrQ9QYEMu+9",
	"9OFbPxyuuX2g7sLv4D1jjTdXRvSLFXUuuwdPiYfcEWpe9WkJx+3IL5F7WG44/yIn0niMfmP/jbA4AetX",
	"/rSTeo4pe2tanVN2zqsFXTOicvfJlkedVmMcCo8UqFdSCSBpUxvltdWSMmIO0PYiYz1IUyFOCsXHwL6z",
	"e58ZuyMJjU0vvFXrM/Ig7vUbfPrxU91MLIaLw9FBH8Gdez3KYyFNYs23eD5+0ui0i1v4m2AIT0hGJ3dv",
	"8O7T7r8BAAD//8cLyPhBUgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
